### PR TITLE
[Frontend] Create Settings Page

### PR DESCRIPTION
**Pull request by brixtuyor**
# Related Links
- http://localhost:8000/settings
- https://app.asana.com/0/1202403928837322/1202403928837347/f

# Description
- Markup for settings where a user can update information

# Notes
- Personal Information tab is done with validation
- TODO: Change Password and Account Options tabs

# Updates
- Included `ñ` as a valid character for names
- Removed account options tab
- Implemented change password feature with validations
- Implemented validation on form submissions

# Screenshots
image

### CODE REVIEW

**Comment by roseaugusto** [comment]
@brixtuyor 
I have confirmations. This is not defined in the task description nor was added as a new task in asana. 
1. Will you include the markup for change password in this pr?
2. What is the content for account settings?
image

**Comment by brixtuyor** [comment]
> 

1. Oh yeah I totally forgot I did not include changing the password in Asana task. I will add it now.
2. I guess Account Options will be the tab for deactivating the account. Is it relevant or no?

**Comment by roseaugusto** [comment]
> 2. I guess Account Options will be the tab for deactivating the account. Is it relevant or no?

It's up to you if you want to include this feature, but if you will include, I suggest change "Personal Information" to "Account Details" and put the button for deactivating account there as well because one button in a whole Account Options section is too spacious in terms of UI/UX design though.


One thing, please change your regex for validation here. Currently it cannot accept `ñ` character. Please take consideration to other symbols as well that can be use for a name.
image

**Comment by brixtuyor** [comment]
> It's up to you if you want to include this feature, but if you will include, I suggest change "Personal Information" to "Account Details" and put the button for deactivating account there as well because one button in a whole Account Options section is too spacious in terms of UI/UX design though.

 I see, decided to remove the option entirely.

> One thing, please change your regex for validation here. Currently it cannot accept `ñ` character. Please take consideration to other symbols as well that can be use for a name. image

Gotcha, the validation now accepts `ñ` as a valid character

**Review by roseaugusto — APPROVED** [review]
Approved!

**Pull request merged**
